# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('geography', models.CharField(max_length=50)),
            ],
        ),
    ]
